### PR TITLE
Add BrimorLabs Cedarpelta Live Response

### PR DESCRIPTION
**Pull request by vxsh4d0w**
Add BrimorLabs Cerdapelta Live Response collection tools.

### CODE REVIEW

**Review by vxsh4d0w — COMMENTED** [review]
Fixed typo error

**Review by vxsh4d0w — COMMENTED** [review]
Fixed a typo error

**Comment by digitalsleuth** [comment]
Hi @vxsh4d0w, the tool looks interesting, however there are a few more typos in the PR. The tool itself is `cedar`pelta, but you have `cerda`pelta instead. It also looks like you missed using the folder you created in the `cerda`pelta-folder-move section for the file shortcut. I'd also change the Category to "Windows Analysis", as that's the organizational structure for the tools. 

Once I'm back at my machine I'll review again and merge accordingly.

Cheers!

**Comment by vxsh4d0w** [comment]
Thanks and sorry for the typo errors. Promise to be more attentive on next pull :) For the category, don't know what suggest because the package contains also the tool for Unix/Linux and MacOs. :)

**Review by vxsh4d0w — COMMENTED** [review]
After a final review, all typo erros have been fixed.

**Comment by digitalsleuth** [comment]
Looks good. Will require a couple of minor changes, but I'll merge and issue a new release shortly!

**Pull request merged**
