### PR TITLE
Add Magnet Response Tool

### PR DESCRIPTION
**Pull request by vxsh4d0w**
Add new Magnet response tool to collect and preserve critical data relevant to incident response investigations

### CODE REVIEW

**Review by vxsh4d0w — COMMENTED** [review]
Changed category

**Comment by digitalsleuth** [comment]
Can you confirm the URL? I'm unable to download it from the one provided in the state. Also, I see no mention of Magnet RESPONSE in their Free Tool listing or on their website. Can you provide more information about this?

**Comment by digitalsleuth** [comment]
Found the issue, the "V" in "V150" should actually be lowercase. Reviewing the tool now.

**Comment by vxsh4d0w** [comment]
Here is the download link: https://storage.googleapis.com/mfi-files/free_tools/MagnetRESPONSE/MagnetRESPONSEv150.zip and here the announcement: https://www.magnetforensics.com/resources/magnet-response/ and video: https://www.youtube.com/watch?app=desktop&v=yS3tccKpyU8

**Review by vxsh4d0w — COMMENTED** [review]
Fixed version typo error

**Comment by digitalsleuth** [comment]
Looks good. Will merge and generate a new release in the next 15 minutes or so.

**Comment by digitalsleuth** [comment]
Thanks for introducing this! For the future, a single PR on this repo will be easier than submitting one for this, CRA-WIN and CPC-WIN. I have some automation in the background which resolves this if the same tool is going into all three.

Shortly in the future, this will be the sole source for the states, and the themes will be customized during install instead of pulling from separate locations.

**Comment by RP5406** [comment]
You know what sucks about MagnetResponse? No /help no silent switch. I did try /accepteula and that one worked.

**Comment by digitalsleuth** [comment]
Yeah, the /accepteula switch is a default with most of their tools.

**Comment by RP5406** [comment]
I feel like having /help or /? is standard practice but I'm no programmer.

**Comment by RP5406** [comment]
Are either one of you aware of a /silent switch or something to allow me to bypass the Exit prompt automatically in Magnet Response?

**Pull request merged**
