### PR TITLE
Create memprocfs-analyzer.sls

### PR DESCRIPTION
**Pull request by vxsh4d0w**

### CODE REVIEW

**Comment by digitalsleuth** [comment]
Hi @vxsh4d0w , this is great! I'll run some testing and merge this tonight if the tests pass.
Cheers!

**Comment by digitalsleuth** [comment]
Hello again @vxsh4d0w , just giving you a heads up, after a bit of testing, I'll need to make some additions to the structure of the state files in order for the application to fully install from the beginning instead of installing the requirements on first run. This won't be done tonight, but should be ready in the next day or two.

**Comment by digitalsleuth** [comment]
Hi @vxsh4d0w , quite a bit of work had to go into making [MemProcFS-Analyzer](https://github.com/digitalsleuth/winfor-salt/blob/main/winfor/standalones/memprocfs-analyzer.sls) work, which ended up being a bit more than was in your pull requests.

Since the PS script itself didn't have a means to install its requirements automatically (in an automated fashion, without human interaction), I had to build a full state to download all requirements, unpack / install them, and make the tool usable offline (so that it didn't exit when no internet connection was detected).

That being said, MemProcFS-Analyzer is now available. Cheers!

**Comment by vxsh4d0w** [comment]
I apologize for the delay in my answer. Unfortunately, MemProcFs-Analyzer requires to download various tool and i realized later that maybe someone won't use internet connection so it was better to create a dedicated offline configuration. Thanks again for your awesome job mate :)

**Pull request closed without merging**
